### ISSUE TITLE
Failed to activate the valhalla package

### ISSUE THREAD

**Issue by patosz** [Bat41/valhalla#1]
Steps to reproduce :

1. Launch Atom

**Atom Version**: 1.8.0
**System**: Unknown Windows Version -> Windows 10 Professionnal x64
**Thrown From**: [valhalla](https://github.com/Bat41/valhalla) package, v0.8.0

### Stack Trace

Failed to activate the valhalla package

```
At Cannot read property 'knownSymbols' of undefined

TypeError: Cannot read property 'knownSymbols' of undefined
    at new ValaProvider (C:/Users/patri/.atom/packages/valhalla/lib/provider.js:38:48)
    at Object.activate (C:/Users/patri/.atom/packages/valhalla/lib/super-vala.js:76:25)
    at Package.module.exports.Package.activateNow (C:\Users\patri\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:183:20)
    at C:\Users\patri\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\patri\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\patri\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\patri\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\patri\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\patri\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\patri\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\patri\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\patri\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\patri\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, vundefined
file-icons, v1.7.13
language-vala, v0.2.0
valhalla, v0.8.0

# Dev
No dev packages
```

**Comment by Bat41** [comment]
Thanks for the bug report '. I'll try to fix it as soon as possible.

**Comment by Bat41** [comment]
I think it should be OK now.

**Comment by patosz** [comment]
After the update to 0.8.2 and fixing the vala path, everything works fine. Thank you.
