### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of null

### ISSUE THREAD

**Issue by benwaffle** [Bat41/valhalla#20]
To reproduce:

1. create new class

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: "Arch Linux"
**Thrown From**: [valhalla](https://github.com/Bat41/valhalla) package, v0.14.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of null

```
At /home/ben/.atom/packages/valhalla/lib/generator.js:56

TypeError: Cannot read property 'getPath' of null
    at Generator.createEditor (/home/ben/.atom/packages/valhalla/lib/generator.js:56:83)
    at Generator.genClass (/home/ben/.atom/packages/valhalla/lib/generator.js:39:14)
    at Generator.gen (/home/ben/.atom/packages/valhalla/lib/generator.js:14:22)
    at /home/ben/.atom/packages/valhalla/lib/valhalla.js:62:28
    at atom-text-editor.<anonymous> (/home/ben/.atom/packages/valhalla/lib/input-view.js:38:17)
```

### Commands

```
     -0:19.3.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:16.2.0 valhalla:new-class (atom-text-editor.editor.vim-mode.normal-mode)
     -0:13.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.5.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:09.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:09.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:09.3.0 valhalla:new-class (atom-text-editor.editor.mini.is-focused)
     -0:06.8.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:06.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:06.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:06.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:04.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.1.0 valhalla:new-class (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:02.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.2.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:00.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "language-objective-c",
      "bookmarks",
      "background-tips",
      "exception-reporting",
      "welcome"
    ]
  },
  "valhalla": {
    "firstTime": false,
    "glibVersion": "2.48.2"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (active)
atom-html-preview, v0.1.22 (active)
atom-jade, v0.3.0 (active)
atom-live-server, v1.2.5 (inactive)
atom-pair, v2.0.10 (active)
auto-detect-indentation, v1.2.0 (active)
autoclose-html, v0.23.0 (active)
autocomplete-glsl, v0.2.3 (active)
autocomplete-html-entities, v0.1.0 (active)
editorconfig, v1.4.1 (active)
indentation-indicator, v1.0.0 (active)
language-autotools, v2.0.1 (active)
language-cmake, v0.2.0 (active)
language-glsl, v2.0.1 (active)
language-javascript-jsx, v0.3.7 (active)
language-meson, v0.1.0 (active)
language-patch, v1.2.0 (active)
language-scala, v1.1.6 (active)
language-vala-modern, v0.3.2 (active)
linter, v1.11.18 (active)
linter-eslint, v7.3.2 (active)
merge-conflicts, v1.4.4 (active)
minimap, vundefined (active)
minimap-git-diff, v4.3.1 (active)
php-twig, v4.0.0 (active)
rain-syntax, v1.0.2 (inactive)
rain-ui, v1.0.1 (inactive)
valhalla, v0.14.0 (active)
vim-mode, v0.65.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (inactive)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (inactive)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Bat41** [comment]
Thanks for the bug report. I'll try to fix it for the next release. :)
