### ISSUE TITLE
New class action causes: Uncaught TypeError: Arguments to CompositeDisposable.add must have a .dispose() method

### ISSUE THREAD

**Issue by andrewloz** [Bat41/valhalla#21]
[Enter steps to reproduce below:]

1. Trigger new class action
2. Type class name and enter... that's it!

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Ubuntu 16.04.1
**Thrown From**: [valhalla](https://github.com/Bat41/valhalla) package, v0.14.0

### Stack Trace

Uncaught TypeError: Arguments to CompositeDisposable.add must have a .dispose() method

```
At /opt/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/opt/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/opt/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at new CompositeDisposable (/opt/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:19:14)
    at /opt/atom/resources/app.asar/src/workspace.js:265:29
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/opt/atom/resources/app.asar/src/pane-container.js:388:27)
    at /opt/atom/resources/app.asar/src/pane-container.js:372:28
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.addItem (/opt/atom/resources/app.asar/src/pane.js:491:20)
    at Generator.createEditor (/home/andrewl/.atom/packages/valhalla/lib/generator.js:58:40)
    at Generator.genClass (/home/andrewl/.atom/packages/valhalla/lib/generator.js:39:14)
    at Generator.gen (/home/andrewl/.atom/packages/valhalla/lib/generator.js:14:22)
    at /home/andrewl/.atom/packages/valhalla/lib/valhalla.js:62:28
    at atom-text-editor.<anonymous> (/home/andrewl/.atom/packages/valhalla/lib/input-view.js:38:17)
```

### Commands

```
     -0:23.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:21.4.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:11.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:05.1.0 valhalla:new-class (atom-text-editor.editor)
     -0:00.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "term",
      "symbols-view",
      "goto",
      "symbols-view-plus"
    ],
    "themes": [
      "spacegray-atom-dark-ui",
      "base16-ocean-dark-spacegray-lighter-invisibles"
    ],
    "useReactEditor": true
  },
  "valhalla": {
    "firstTime": false
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8 (active)
atom-ctags, v5.0.0 (active)
atom-dark-ui-slim, v0.47.1 (inactive)
atom-soda-dark-ui, v1.1.0 (inactive)
autocomplete-paths, v1.0.2 (active)
base16-ocean-dark, v1.2.0 (inactive)
base16-ocean-dark-spacegray, v0.12.0 (inactive)
base16-ocean-dark-spacegray-lighter-invisibles, v0.3.0 (active)
base16-ocean-dark-syntax-theme, v0.1.9 (inactive)
base16-ocean-light-syntax, v0.2.0 (inactive)
build, v0.65.0 (active)
build-systems, v0.5.0 (active)
busy, v0.7.0 (active)
clean-atom-dark-ui, v0.28.0 (inactive)
editor-settings, v1.1.2 (active)
fizzy, v0.16.0 (inactive)
git-plus, v5.18.0 (active)
goto, v1.7.1 (inactive)
Kimbie-dark, v0.0.0 (inactive)
kimbie-dark, v1.3.1 (inactive)
language-awk, v0.1.11 (active)
language-gdb, v0.3.6 (active)
language-ini, v1.16.0 (active)
language-vala-modern, v0.3.2 (active)
linter, v1.11.16 (active)
linter-lua, v1.0.2 (active)
linter-ruby, v1.2.2 (active)
man, v0.5.0 (inactive)
minimap, v4.24.7 (active)
minimap-color-highlight, v4.1.4 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-highlight-selected, v4.4.0 (active)
monokai, v0.18.0 (inactive)
oceanic-theme, v0.1.2 (inactive)
project-manager, v2.9.7 (active)
project-switcher, v0.3.0 (inactive)
regex-railroad-diagram, v0.16.0 (active)
ruby-define-method, v0.2.2 (active)
ruby-syntax-replacer, v0.5.1 (active)
script, v3.10.1 (inactive)
soda-light-ui, v0.2.0 (inactive)
spacegray-atom-dark-syntax, v1.2.0 (inactive)
spacegray-atom-dark-ui, v1.0.0 (active)
spacegray-dark-syntax, v0.2.0 (inactive)
spacegray-dark-ui, v0.12.0 (inactive)
spacegray-light-syntax, v0.1.0 (inactive)
spacegray-light-ui, v0.1.0 (inactive)
spacegray-mocha-ui, v1.0.0 (inactive)
spacegray-peacock-ui, v1.0.0 (inactive)
symbols-view-plus, v0.113.1-plus.5 (inactive)
term2, v0.9.12 (inactive)
unicorn-syntax, v2.2.0 (inactive)
unicorn-ui, v1.2.0 (inactive)
valhalla, v0.14.0 (active)
white-ui, v2.4.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Bat41** [comment]
Thanks for the report. It will normally be fixed in the next version. :)

**Comment by Bat41** [comment]
I think it should be fixed now. I you can confirm, i'll close this issue.
