### ISSUE TITLE
Valhala don't start

### ISSUE THREAD

**Issue by naaando** [Bat41/valhalla#28]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: elementary OS
**Thrown From**: [valhalla](https://github.com/Bat41/valhalla) package, v0.14.0

### Stack Trace

Failed to activate the valhalla package

```
At ENAMETOOLONG: name too long, stat '/home/naaando/Projetos/Vala/Ambrosia/COPYING'

Error: ENAMETOOLONG: name too long, stat '/home/naaando/Projetos/Vala/Ambrosia/COPYING'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at explore (/home/naaando/.atom/packages/valhalla/lib/provider.js:28:24)
    at new ValaProvider (/home/naaando/.atom/packages/valhalla/lib/provider.js:40:13)
    at Object.activate (/home/naaando/.atom/packages/valhalla/lib/valhalla.js:93:25)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:184:19)
    at /usr/share/atom/resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:550:34)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:352:19
    at /usr/share/atom/resources/app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/usr/share/atom/resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/usr/share/atom/resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:173:14)
    at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:358:27)
    at HTMLButtonElement.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -4:13.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -3:04.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:53.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:48.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:46.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:43.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:41.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:41.3.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:40.2.0 core:undo (atom-text-editor.editor.is-focused)
     -1:38.4.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  5x -1:38.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:36.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-preview-plus",
      "markdown-writer",
      "language-gfm",
      "language-vala",
      "autovala-atom"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-material-ui",
      "seti-syntax"
    ]
  },
  "valhalla": {
    "firstTime": false,
    "vapiDir": "/usr/share/vala/vapi/:usr/share/vala-0.32/vapi/"
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.9 (active)
autovala-atom, v0.5.0 (inactive)
isotope-ui, v2.7.1 (inactive)
language-cmake, v0.3.0 (active)
language-markdown, v0.19.1 (active)
language-vala, v0.2.0 (inactive)
language-vala-modern, v0.3.2 (active)
linter, v1.11.18 (active)
linter-markdown, v3.1.0 (active)
markdown-preview-plus, v2.4.0 (inactive)
markdown-writer, v2.6.3 (inactive)
nord-atom-syntax, v0.5.0 (inactive)
nord-atom-ui, v0.9.0 (inactive)
qolor, v0.4.1 (active)
rails-snippets, v2.11.0 (inactive)
seti-syntax, v1.0.1 (active)
seti-ui-beta, v0.1.1 (inactive)
valhalla, v0.14.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

![image](https://cloud.githubusercontent.com/assets/12532760/22701177/14272e18-ed44-11e6-9bf9-0bb98468538d.png)

**Comment by Bat41** [comment]
OK, it's just an exception that's not handled. If the problem is really too annoying I can try to publish a fix now. Else, it will be in the next version (as so many other bug fixes).

**Comment by Bat41** [comment]
Is this problem solved too with the new version?
