### ISSUE TITLE
At parsedDoc[taglet].push is not a function

### ISSUE THREAD

**Issue by SkyzohKey** [Bat41/valhalla#30]
**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: elementary OS
**Thrown From**: [valhalla](https://github.com/Bat41/valhalla) package 0.14.0

### Stack Trace

Failed to activate the valhalla package

```
At parsedDoc[taglet].push is not a function

TypeError: parsedDoc[taglet].push is not a function
    at ScopeManager.parseDoc (/packages/valhalla/lib/scopes.js:533:39)
    at ScopeManager.parse (/packages/valhalla/lib/scopes.js:175:42)
    at explore (/packages/valhalla/lib/provider.js:34:34)
    at explore (/packages/valhalla/lib/provider.js:29:21)
    at explore (/packages/valhalla/lib/provider.js:29:21)
    at explore (/packages/valhalla/lib/provider.js:29:21)
    at /packages/valhalla/lib/provider.js:40:13)
    at Object.activate (/packages/valhalla/lib/valhalla.js:93:25)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-build-waf 0.2.0 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-oss-license 1.1.1 
autocomplete-cmake 0.3.1 
autocomplete-nunjucks 0.5.0 
autovala-atom 0.5.0 
build 0.67.0 
build-cmake 0.8.3 
busy 0.7.0 
language-cmake 0.3.0 
language-ini-desktop 1.18.3 
language-nunjucks 4.1.0 
language-vala-modern 0.3.2 
minimap 4.26.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.1 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
valhalla 0.14.0 
```

**Comment by Bat41** [comment]
I don't how did you manage to get this error, that's really strange. Did you wrote an empty taglet in your doc, e.g.

```vala
/**
* A method
*
* @     I break everything! ^^
*/
void main () {}
```

Or anything else not "normal" ?

**Comment by SkyzohKey** [comment]
Nan, tout est normal et valide, mais même si un tag est invalide, le plugin devrait simplement l'ignorer au lieu d'envoyer une erreur c:

**Comment by Bat41** [comment]
En fait c'est vraiment super bizarre. Je ne vois pas d'où ça peut venir. Est-ce que tu pourrais me donner un lien vers le projet dans lequel tu était quand ça a planté pour voir ce qui peut faire planter ça.

Sinon je suis en train de bosser sur une nouvelle version avec de vrais messages d'erreurs, un vrai parseur/lexeur (et pas juste un découpage hasardeux à coup de regex ultra-complexes) qui devrait régler pas mal de problèmes avec la version actuelle. Dont celui-ci je pense.

**Comment by SkyzohKey** [comment]
Ça foire tout le temps quand je suis sur les fichiers de mon client Tox: https://github.com/SkyzohKey/Konv :

**Comment by Bat41** [comment]
Je vois vraiment pas pourquoi ça plante... Tu écris pas ta doc comme Valadoc/Valhalla [s'y attendent](https://valadoc.org/markup.htm), mais ça devrait pas planter pour autant. Si t'as pas peur de bidouiler un peu je peux te faire une solution provisoire en attendant la prochaine version (genre il faut que t'ailles modifier le code de valhalla qui est installé sur ton ordi).

**Comment by Bat41** [comment]
Normalement la 1.0.0 doit régler ça vu que le code d'où l'erreur vient n'existe plus. Je ferme.
