### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by PDDStudio** [Bat41/valhalla#32]
[Enter steps to reproduce:]

1. Update valhalla to latest version 
2. Try opening the `Vala Documentation`by clicking the icon in the toolbar

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [valhalla](https://github.com/Bat41/valhalla) package 1.0.4

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/pddstudio/.atom/packages/valhalla/lib/views/doc/home.js:33

TypeError: Cannot read property 'path' of undefined
  at Home.render (/packages/valhalla/lib/views/doc/home.js:68:69)
  at Object.initialize (/packages/valhalla/node_modules/etch/dist/component-helpers.js:60:34)
  at Home.init (/packages/valhalla/lib/views/etch-component.js:39:25)
  at Home.EtchComponent (/packages/valhalla/lib/views/etch-component.js:28:12)
  at /packages/valhalla/lib/views/doc/home.js:44:70)
  at ComponentWidget.init (/packages/valhalla/node_modules/etch/dist/component-widget.js:58:24)
  at createElement (/packages/valhalla/node_modules/virtual-dom/vdom/create-element.js:19:22)
  at createElement (/packages/valhalla/node_modules/virtual-dom/vdom/create-element.js:39:25)
  at Object.initialize (/packages/valhalla/node_modules/etch/dist/component-helpers.js:68:64)
  at _default.init (/packages/valhalla/lib/views/etch-component.js:39:25)
  at /packages/valhalla/lib/views/doc/doc.js:85:10)
  at /packages/valhalla/lib/valhalla.js:164:16
  at Workspace.module.exports.Workspace.openURIInPane (/app.asar/src/workspace.js:501:22)
  at Workspace.module.exports.Workspace.open (/app.asar/src/workspace.js:436:19)
  at /packages/valhalla/lib/valhalla.js:178:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
  at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
  at executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:123:19)
  at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:82:9)

```

### Commands

```
     -5:50.1.0 settings-view:open (input.hidden-input)
     -5:44.3.0 core:confirm (input.hidden-input)
     -4:34.4.0 command-palette:toggle (input.hidden-input)
  2x -4:25.8.0 core:move-down (input.hidden-input)
  5x -4:22.6.0 core:backspace (input.hidden-input)
     -4:20.2.0 core:confirm (input.hidden-input)
     -4:20.2.0 tree-view:show (input.hidden-input)
     -1:37.1.0 valhalla:documentation (input.hidden-input)
```

### Non-Core Packages

```
api-workbench 0.8.43 
atom-ternjs 0.17.2 
autocomplete-modules 1.6.7 
builder 0.0.1 
clipboard-ide 0.7.0 
css-color-underline 1.0.1 
editorconfig 2.2.2 
es6-javascript 1.0.0 
format-shell 2.0.0 
javascript-snippets 1.2.1 
json-colorer 1.0.0 
language-babel 2.55.6 
language-unix-shell 0.40.1 
language-vala-modern 0.3.2 
linter 1.11.23 
linter-eslint 8.1.2 
linter-shellcheck 1.4.3 
minimap-pigments 0.2.2 
nord-atom-syntax 0.6.0 
nord-atom-ui 0.10.1 
nuclide 0.208.0 
pigments 0.39.0 
process-palette 0.12.0 
project-plus 0.9.0 
selly-syntax-ide 2.0.2 
selly-ui-ide 3.1.0 
TerminalColor 1.1.0 
tool-bar 1.0.1 
tool-bar-main 0.0.10 
valhalla 1.0.4 
```

**Comment by PDDStudio** [comment]
In addition:
Maybe this could have something to do with #31 (path mapping on OSX) as well?

**Comment by PDDStudio** [comment]
One more issue (occurs once I start typing - and repeats on every tap)

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [valhalla](https://github.com/Bat41/valhalla) package 1.0.4


### Stack Trace

Uncaught TypeError: Cannot read property 'explore' of undefined

```
At /Users/pddstudio/.atom/packages/valhalla/lib/vala-provider.js:26

TypeError: Cannot read property 'explore' of undefined
  at ValaProvider.getSuggestions (/packages/valhalla/lib/vala-provider.js:60:23)
  at /app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:333:54
  at Array.forEach (native)
  at AutocompleteManager.getSuggestionsFromProviders (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:309:17)
  at AutocompleteManager.findSuggestions (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:298:19)

```

### Commands

```
     -9:02.9.0 settings-view:open (input.hidden-input)
     -8:57.2.0 core:confirm (input.hidden-input)
     -7:47.3.0 command-palette:toggle (input.hidden-input)
  2x -7:38.6.0 core:move-down (input.hidden-input)
  5x -7:35.5.0 core:backspace (input.hidden-input)
     -7:33 core:confirm (input.hidden-input)
     -7:33 tree-view:show (input.hidden-input)
     -4:49.9.0 valhalla:documentation (input.hidden-input)
     -0:15.3.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
api-workbench 0.8.43 
atom-ternjs 0.17.2 
autocomplete-modules 1.6.7 
builder 0.0.1 
clipboard-ide 0.7.0 
css-color-underline 1.0.1 
editorconfig 2.2.2 
es6-javascript 1.0.0 
format-shell 2.0.0 
javascript-snippets 1.2.1 
json-colorer 1.0.0 
language-babel 2.55.6 
language-unix-shell 0.40.1 
language-vala-modern 0.3.2 
linter 1.11.23 
linter-eslint 8.1.2 
linter-shellcheck 1.4.3 
minimap-pigments 0.2.2 
nord-atom-syntax 0.6.0 
nord-atom-ui 0.10.1 
nuclide 0.208.0 
pigments 0.39.0 
process-palette 0.12.0 
project-plus 0.9.0 
selly-syntax-ide 2.0.2 
selly-ui-ide 3.1.0 
TerminalColor 1.1.0 
tool-bar 1.0.1 
tool-bar-main 0.0.10 
valhalla 1.0.4 
```

**Comment by Bat41** [comment]
Can you see any other error when you open the dev tools (with Cmd+Shift+I I think)?

**Comment by PDDStudio** [comment]
@Bat41 the console output in Chrome Dev Tools doesn't display much information. (Actually it does, but only by spamming the same error continuously :smile: 

Basically those are the errors which occur:

`
valhalla.js [sm]:193 TypeError: Cannot read property 'begin' of null(…)(anonymous function) @ valhalla.js [sm]:193
`

`
/Users/pddstudio/.atom/packages/valhalla/lib/valhalla.js:290 TypeError: Cannot read property 'begin' of null(…)(anonymous function) @ /Users/pddstudio/.atom/packages/valhalla/lib/valhalla.js:290
`

`
/Users/pddstudio/.atom/packages/valhalla/lib/valhalla.js:260 TypeError: Cannot read property 'begin' of null(…)(anonymous function) @ /Users/pddstudio/.atom/packages/valhalla/lib/valhalla.js:260
`

I hope this helps anyways...
If there's anything else I can do, just let me know!

**Comment by Bat41** [comment]
Do you still have the problem [busy package](https://atom.io/packages/busy) and restart Atom?

**Comment by PDDStudio** [comment]
@Bat41 Installing `busy` fixed it. The `Documentation` for installed `*.vapis` is working fine so far without any crashes as of now. 
In addition I can also confirm that the `auto completion` is finally working! (The first time, and I'm using this plugin since about half a year or so :joy: )

If you need additional help for fixing these bugs on Mac (or need someone to test it) - just let me know

**Comment by Bat41** [comment]
Great! I'll publish a patch soon. Thanks for your help. 🙂

**Comment by Bat41** [comment]
Just published the patch.
