### ISSUE TITLE
Uncaught TypeError: Cannot read property 'explore' of undefined

### ISSUE THREAD

**Issue by PDDStudio** [Bat41/valhalla#35]
[Enter steps to reproduce:]

1.Create a new file and start editing it

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [valhalla](https://github.com/Bat41/valhalla) package 1.0.5

### Stack Trace

Uncaught TypeError: Cannot read property 'explore' of undefined

```
At /Users/pddstudio/.atom/packages/valhalla/lib/vala-provider.js:26

TypeError: Cannot read property 'explore' of undefined
    at ValaProvider.getSuggestions (/packages/valhalla/lib/vala-provider.js:26:21)
    at /app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:333:54
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:309:17)
    at AutocompleteManager.findSuggestions (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:298:19)
```

### Commands

```
     -3:54.1.0 editor:move-to-beginning-of-word (input.hidden-input)
     -3:53.7.0 core:move-left (input.hidden-input)
  2x -3:51.9.0 editor:move-to-end-of-word (input.hidden-input)
  2x -3:51 core:move-left (input.hidden-input)
  3x -3:39.9.0 core:backspace (input.hidden-input)
     -3:35 pane:show-next-recently-used-item (input.hidden-input)
     -3:34.9.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -3:32 pane:show-next-recently-used-item (input.hidden-input)
     -3:31.9.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -3:29.5.0 core:move-left (input.hidden-input)
     -1:37 tree-view:add-folder (span.name.icon.icon-file-directory)
  4x -1:32.8.0 core:move-left (input.hidden-input)
     -1:29.8.0 core:confirm (input.hidden-input)
     -1:19.1.0 tree-view:add-file (span.name.icon.icon-file-directory)
  8x -1:12.6.0 core:backspace (input.hidden-input)
     -0:13.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
api-workbench 0.8.43 
atom-ternjs 0.18.1 
autocomplete-modules 1.6.7 
builder 0.0.1 
busy 0.7.0 
clipboard-ide 0.7.0 
css-color-underline 1.0.1 
editorconfig 2.2.2 
es6-javascript 1.0.0 
format-shell 2.0.0 
javascript-snippets 1.2.1 
json-colorer 1.0.0 
language-babel 2.55.6 
language-unix-shell 0.40.1 
language-vala-modern 0.3.2 
linter 1.11.23 
linter-eslint 8.1.2 
linter-shellcheck 1.4.3 
minimap-pigments 0.2.2 
nord-atom-syntax 0.6.0 
nord-atom-ui 0.10.1 
nuclide 0.208.0 
pigments 0.39.0 
process-palette 0.12.0 
project-plus 0.9.0 
selly-syntax-ide 2.0.2 
selly-ui-ide 3.1.0 
TerminalColor 1.1.0 
tool-bar 1.0.1 
tool-bar-main 0.0.10 
valhalla 1.0.5 
```

**Comment by PDDStudio** [comment]
I'm just reporting this here to have it at least noted down once. I'll further investigate in _when_ this error occurs. I will post any results into this ticket.

**Comment by Bat41** [comment]
Thanks for the report. I can reproduce and I know where does this problem comes from. I'll publish a patch in the 1.1.

**Comment by Bat41** [comment]
Thanks for the report. I can reproduce and I know where does this problem comes from. I'll publish a patch in the 1.1.

**Comment by Bat41** [comment]
I published 1.1.0, it should work now.

**Comment by PDDStudio** [comment]
@Bat41 once again, thanks in advance for the fast fix!
One more thing - is it on purpose that project internal classes don't pop up for auto completion? 
As far as I found out there is some strange behavior with classes/functions  popup window when using another class from the same namespace as the current one. It always suggests to import the namespace - which is actually the same of the class I'm working on so it wouldn't make any sense

**Comment by Bat41** [comment]
> One more thing - is it on purpose that project internal classes don't pop up for auto completion?

No, it's a bug. I opened another issue: #37

> As far as I found out there is some strange behavior with classes/functions popup window when using another class from the same namespace as the current one. It always suggests to import the namespace - which is actually the same of the class I'm working on so it wouldn't make any sense

Yes, it's because I don't include the current namespace in the "used" ones. I'll fix it too (see issue #38). 🙂

**Comment by PDDStudio** [comment]
I'll keep an eye on them ;) thanks!

**Comment by bjaminn** [comment]
[Enter steps to reproduce:]

The problem seems to exist again in 1.1.2

1. Same case as before.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 17.04
**Thrown From**: [valhalla](https://github.com/Bat41/valhalla) package 1.1.2


### Stack Trace

Uncaught TypeError: Cannot read property 'explore' of undefined

```
At ~/.atom/packages/valhalla/lib/vala-provider.js:26

TypeError: Cannot read property 'explore' of undefined
    at ValaProvider.getSuggestions (/packages/valhalla/lib/vala-provider.js:26:21)
    at /app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:333:54
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:309:17)
    at AutocompleteManager.findSuggestions (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:298:19)
    at /app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:270:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  2x -0:05.6.0 autocomplete-plus:activate (input.hidden-input)
```

### Non-Core Packages

```
language-vala-modern 0.3.2 
valhalla 1.1.2 
```

**Comment by Bat41** [comment]
Sorry, I don't have time to work on it now. A workaround is to write something in your file (a class, an interface, a function...) that is valid (= compiles) and to reload Atom with Ctrl+Shift+F5

**Comment by wbuarque** [comment]
This workaround seems to work only in a fresh new file.

**Comment by Bat41** [comment]
What do you mean by "simple files"?

**Comment by wbuarque** [comment]
Actually i tried with a new class and a single main method and it works. For instance [this](https://github.com/elementary/photos/blob/master/src/AppWindow.vala) file presents the issue. I don't know if there are any limitations. Thanks.

**Comment by avently** [comment]
@Bat41 i installed your plugin and can't use it because this errors pops up everytime i'm writing something. Do you still work on this plugin? Can i somehow fix it myself? Maybe, working workaround or something.

**Comment by Bat41** [comment]
I'm no longer working on this plugin, and I think I will never work on it again. I gess your errors comes from a bug in the plugin, but I won't fix it. I don't have enough time to maintain all my FOSS projects, and valhalla/vala is no longer my priority. Sorry. :(
